### ISSUE TITLE
BufferUnderflowException thrown when fetching data

### ISSUE THREAD

**Issue by ud3sh** [mtpettyp/jdbc-redis#4]
A BufferUnderflowException occurs intermittently when decoding the response string in RESPDecoder.  The orginal cause of the issue seems to be in RedisSocketIO#sendRaw.  In particular, the following exit condition on the while loop is incorrect
`while(this.fromServerSocket.ready()  || sb.length() == 0) `
this.fromServerSocket.ready() could evaluate to false even when there are more bytes available in the response.   This leads to the following exception in RESPDecoder because there are less bytes available than expected (as specified in the first line of the response)
```
java.nio.BufferUnderflowException
	at java.nio.CharBuffer.get(CharBuffer.java:688)
	at java.nio.CharBuffer.get(CharBuffer.java:715)
	at br.com.svvs.jdbc.redis.RESPDecoder.parseBulkString(RESPDecoder.java:57)
```

**Comment by ud3sh** [comment]
Should be fixed by https://github.com/mtpettyp/jdbc-redis/pull/5
